if (!require("remotes", quietly = TRUE)) install.packages("remotes")
if (!require("kableExtra", quietly = TRUE)) install.packages("kableExtra")
if (!require("purrr", quietly = TRUE)) install.packages("purrr")
if (!require("stringr", quietly = TRUE)) install.packages("stringr")
remotes::install_github("chroetz/ConfigOpts")
remotes::install_github("chroetz/DEEBtrajs")
remotes::install_github("chroetz/DEEBpath")
remotes::install_github("chroetz/DEEBplots")
remotes::install_github("chroetz/DEEBdata")
remotes::install_github("chroetz/DEEBeval")
