if (!require("remotes", quietly = TRUE)) install.packages("remotes")
if (!require("kableExtra", quietly = TRUE)) install.packages("kableExtra")
if (!require("purrr", quietly = TRUE)) install.packages("purrr")
if (!require("rlang", quietly = TRUE)) install.packages("rlang")
if (!require("stringr", quietly = TRUE)) install.packages("stringr")
if (!require("tidyr", quietly = TRUE)) install.packages("tidyr")
if (!require("dplyr", quietly = TRUE)) install.packages("dplyr")
if (!require("tibble", quietly = TRUE)) install.packages("tibble")
if (!require("RANN", quietly = TRUE)) install.packages("RANN")
if (!require("Rcpp", quietly = TRUE)) install.packages("Rcpp")
remotes::install_github("chroetz/FastKNN")
remotes::install_github("chroetz/ConfigOpts")
remotes::install_github("chroetz/DEEButil")
remotes::install_github("chroetz/DEEBtrajs")
remotes::install_github("chroetz/DEEBpath")
remotes::install_github("chroetz/DEEBplots")
remotes::install_github("chroetz/DEEBdata")
remotes::install_github("chroetz/DEEBeval")
remotes::install_github("chroetz/DEEBesti")
remotes::install_github("chroetz/DEEBcmd")

packageVersion("FastKNN")
packageVersion("ConfigOpts")
packageVersion("DEEButil")
packageVersion("DEEBtrajs")
packageVersion("DEEBpath")
packageVersion("DEEBcmd")
packageVersion("DEEBplots")
packageVersion("DEEBdata")
packageVersion("DEEBeval")
packageVersion("DEEBesti")
